# Generated by Django 3.2.8 on 2021-11-23 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cleintID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('clientname', models.CharField(max_length=100)),
                ('clienttype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SPVUser',
            fields=[
                ('userID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('officephone', models.CharField(max_length=100)),
                ('cellphone', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=10)),
                ('clientID', models.ManyToManyField(to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postalcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('faxnumber', models.CharField(max_length=100)),
                ('clientID', models.ManyToManyField(to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificateNumber', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('reportNumber', models.IntegerField()),
                ('issueDate', models.DateField()),
                ('standardID', models.IntegerField()),
                ('modelnumber', models.IntegerField()),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('userID', models.ManyToManyField(to='backend.SPVUser')),
            ],
        ),
    ]
