# Generated by Django 3.2.8 on 2021-11-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issueDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='modelnumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='reportNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='standardID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='clienttype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='faxnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='postalcode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spvuser',
            name='cellphone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spvuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spvuser',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spvuser',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spvuser',
            name='officephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
