# Generated by Django 3.2.8 on 2021-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211122_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='locationID',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
