# Generated by Django 3.2.8 on 2021-11-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211122_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issueDate',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='locationID',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='modelnumber',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='standardID',
        ),
        migrations.AddField(
            model_name='certificate',
            name='clientID',
            field=models.ManyToManyField(to='backend.Client'),
        ),
    ]
