# Generated by Django 3.2.8 on 2021-11-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211122_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cleintID',
            new_name='clientID',
        ),
    ]
